name: Trigger auto deployment for v2ray1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/v2ray1-AutoDeployTrigger-4f750439-ba49-40eb-9afd-99c9173a9d19.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.V2RAY1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.V2RAY1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.V2RAY1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.V2RAY1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.V2RAY1_REGISTRY_PASSWORD }}
          containerAppName: v2ray1
          resourceGroup: v2ray
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


